# Generated by Django 5.0.2 on 2024-02-23 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'invalid': 'Email inválido.', 'unique': 'Email en uso.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'invalid': 'Contraseña inválida.'}, validators=[django.core.validators.RegexValidator(regex='^(?=.*.)(?=.*\\d).{8,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, editable=False, error_messages={'invalid': 'Nombre de usuario inválido.', 'max_length': 'Nombre de usuario demasiado largo.', 'unique': 'Nombre de usuario en uso.'}, max_length=25, unique=True),
        ),
    ]
