# Generated by Django 5.0.2 on 2024-02-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'invalid': 'Nombre de usuario inválido.', 'max_length': 'Nombre de usuario demasiado largo.', 'unique': 'Nombre de usuario en uso.'}, max_length=25, unique=True),
        ),
    ]
